import cv2 as cv
import numpy as np
img=cv.imread("ged.jpg")
cv.imshow("orginal",img)
guassian=cv.GaussianBlur(img,(5,5),100)
cv.imshow("Guasinblur",guassian)
median=cv.medianBlur(img,15)
cv.imshow("MedianBlur",median)
bilateral= cv.bilateralFilter(img,7,150,150)
cv.imshow("BilateralBlur",bilateral)
bord=cv.copyMakeBorder(img,7,8,15,12,cv.BORDER_CONSTANT,None,value=155)
cv.imshow("Borderconsatnt",bord)
border=cv.copyMakeBorder(img,207,108,205,112,cv.BORDER_REFLECT,None)
cv.imshow("borderreflect",border)
img1=cv.cvtColor(img,cv.COLOR_BGR2GRAY)
cv.imshow("Gray scale",img1)
edge=cv.Canny(img,50,60)
cv.imshow("Edge",edge)
h,w,d=img.shape
scale=cv.resize(img,(int(w/2),int(h/2)),interpolation=cv.INTER_AREA)
cv.imshow("shrinking",scale)
scale1=cv.resize(img,(int(w*2),int(h*2)),interpolation=cv.INTER_CUBIC)
cv.imshow("zooming",scale1)
T=np.float32([[1,0,20],[0,1,30]])
translate=cv.warpAffine(img,T,(w,h))
cv.imshow("Translating",translate)
circle=cv.circle(img,(100,60),30,(120,120,120),-2)
cv.imshow("circle",circle)
